name: Publish qCHeff to PyPI

on:
  release:
    types: [published]

jobs:
  pypi-release:
    name: Publish to PyPI
    runs-on: ubuntu-latest


    environment:
      name: pypi
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # Install a specific version of uv.
          version: "0.8.15"
          # Enable cache to speed up the build
          enable-cache: true

      - name: Build release distributions
        run: uv build

      - name: Publish
        run: uv publish
 